import type { Metadata } from "next";
import { Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import WhatsAppButton from "./components/WhatsAppButton";
import ToastProvider from "./components/ToastProvider";
import ContactUs from "./components/ContactUs";
import OurPartners from "./components/OurPartners";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Trendwave",
  description: "Generated by create next app",
  icons: {
    icon: "/browser_logo.PNG",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={`${inter.variable} ${geistMono.variable} antialiased font-(family-name:--font-inter)`}
      >
        <ToastProvider />
        <Navbar />
        <main className="pt-0">{children}</main>
        <ContactUs />
      <OurPartners />
        <Footer />
        <WhatsAppButton />
      </body>
    </html>
  );
}
