import fs from "node:fs";
import path from "node:path";

const root = process.cwd();

function exists(relativePath) {
  return fs.existsSync(path.join(root, relativePath));
}

function read(relativePath) {
  return fs.readFileSync(path.join(root, relativePath), "utf8");
}

const errors = [];
const warnings = [];

function fail(message) {
  errors.push(message);
}

function warn(message) {
  warnings.push(message);
}

const requiredFiles = [
  "lib/seo.ts",
  "app/robots.ts",
  "app/sitemap.ts",
  "app/layout.tsx",
  "app/opengraph-image.tsx",
  "app/components/JsonLd.tsx",
  "content/products.ts",
  "content/articles.ts",
  "app/products/[slug]/page.tsx",
  "app/blog/page.tsx",
];

for (const file of requiredFiles) {
  if (!exists(file)) {
    fail(`Missing required file: ${file}`);
  }
}

if (exists("app/layout.tsx")) {
  const layout = read("app/layout.tsx");
  if (!layout.includes("metadataBase")) fail("Root layout is missing metadataBase.");
  if (layout.includes("Generated by create next app")) fail("Placeholder description still present.");
  if (!layout.includes("en-IN")) warn("html lang may not be en-IN.");
  if (!layout.includes("JsonLd")) fail("Root layout is missing JsonLd.");
}

if (exists("lib/seo.ts")) {
  const seo = read("lib/seo.ts");
  if (!seo.includes("https://www.trendwavetech.com")) fail("Canonical domain missing in lib/seo.ts.");
  if (!seo.includes("TrendWave Technologies Pvt Ltd")) fail("Legal name missing in lib/seo.ts.");
  if (!seo.includes("Welldone Tech Park")) fail("NAP address missing in lib/seo.ts.");
}

if (exists("content/products.ts")) {
  const products = read("content/products.ts");
  const slugs = [...products.matchAll(/slug: "([^"]+)"/g)].map((match) => match[1]);
  const unique = new Set(slugs);
  if (slugs.length !== unique.size) fail("Duplicate product slugs.");
  if (/slug:\s*"key-management/.test(products)) {
    warn("Key management slug found; confirm the offering exists.");
  }
  const requiredSlugs = [
    "boom-barriers",
    "tyre-killers",
    "hydraulic-bollards",
    "cctv-installation",
    "anpr",
    "acms",
    "vehicle-monitoring-system",
  ];
  for (const slug of requiredSlugs) {
    if (!unique.has(slug)) fail(`Missing product slug: ${slug}`);
  }
}

if (exists("app/robots.ts")) {
  const robots = read("app/robots.ts");
  if (!robots.includes("/api/")) fail("robots.ts should disallow /api/.");
  if (!robots.includes("sitemap.xml")) fail("robots.ts should include sitemap URL.");
}

const pagesToCheck = [
  ["app/page.tsx", "Home"],
  ["app/services/surveillance/layout.tsx", "Surveillance hub"],
  ["app/services/it-infra/layout.tsx", "IT hub"],
  ["app/services/digital/page.tsx", "Digital hub"],
  ["app/company/layout.tsx", "Company"],
];

for (const [file, label] of pagesToCheck) {
  if (!exists(file)) {
    fail(`${label} file missing: ${file}`);
    continue;
  }
  const source = read(file);
  if (!source.includes("buildPageMetadata") && !source.includes("generateMetadata")) {
    fail(`${label} is missing metadata export.`);
  }
}

const navbar = exists("app/components/Navbar.tsx") ? read("app/components/Navbar.tsx") : "";
if (navbar.includes('href="/terms-conditions"') && navbar.includes("9821801122")) {
  fail("Mobile phone number still appears to point at terms-conditions.");
}

const footer = exists("app/components/Footer.tsx") ? read("app/components/Footer.tsx") : "";
if (footer.includes('href="/services/surveillance"') && footer.includes("productItems")) {
  warn("Footer may still send all products to the surveillance hub.");
}

const baseUrl = process.env.SEO_AUDIT_BASE_URL;

async function crawlIfRequested() {
  if (!baseUrl) {
    warn("SEO_AUDIT_BASE_URL not set; skipped live crawl of robots, sitemap and titles.");
    return;
  }

  const robotsRes = await fetch(new URL("/robots.txt", baseUrl));
  if (!robotsRes.ok) fail(`Live /robots.txt failed: ${robotsRes.status}`);
  const robotsText = await robotsRes.text();
  if (!robotsText.includes("Sitemap:")) fail("Live robots.txt missing Sitemap.");
  if (!robotsText.includes("Disallow: /api/")) fail("Live robots.txt missing /api/ disallow.");

  const sitemapRes = await fetch(new URL("/sitemap.xml", baseUrl));
  if (!sitemapRes.ok) fail(`Live /sitemap.xml failed: ${sitemapRes.status}`);
  const sitemapText = await sitemapRes.text();
  if (!sitemapText.includes("/products/boom-barriers")) fail("Sitemap missing boom-barriers URL.");
  if (sitemapText.includes("/api/contact")) fail("Sitemap includes API URL.");

  const samplePaths = ["/", "/services/surveillance", "/products/anpr", "/blog"];
  const titles = [];
  const descriptions = [];

  for (const samplePath of samplePaths) {
    const res = await fetch(new URL(samplePath, baseUrl));
    if (!res.ok) {
      fail(`Live ${samplePath} returned ${res.status}`);
      continue;
    }
    const html = await res.text();
    const title = html.match(/<title>([^<]*)<\/title>/i)?.[1] ?? "";
    const description =
      html.match(/<meta[^>]*name=["']description["'][^>]*content=["']([^"]*)["']/i)?.[1] ?? "";
    const canonical =
      html.match(/<link[^>]*rel=["']canonical["'][^>]*href=["']([^"]*)["']/i)?.[1] ?? "";
    const h1Count = (html.match(/<h1\b/gi) || []).length;
    if (!title) fail(`${samplePath} missing title.`);
    if (!description) fail(`${samplePath} missing meta description.`);
    if (!canonical) fail(`${samplePath} missing canonical.`);
    if (h1Count !== 1) warn(`${samplePath} has ${h1Count} H1 tags.`);
    if (!html.includes("application/ld+json")) warn(`${samplePath} has no JSON-LD in HTML.`);
    titles.push(title);
    descriptions.push(description);
  }

  if (new Set(titles).size !== titles.length) fail("Duplicate titles found in crawled pages.");
  if (new Set(descriptions).size !== descriptions.length) {
    fail("Duplicate meta descriptions found in crawled pages.");
  }
}

await crawlIfRequested();

console.log("SEO audit");
console.log(`Errors: ${errors.length}`);
console.log(`Warnings: ${warnings.length}`);
for (const error of errors) console.log(`ERROR  ${error}`);
for (const warning of warnings) console.log(`WARN   ${warning}`);

if (errors.length > 0) {
  process.exit(1);
}
